<Project>
  <PropertyGroup>
    <!-- Enable Code Analysis -->
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    
    <!-- Treat warnings as messages (not block build) -->
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    
    <!-- Enable EditorConfig support -->
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
