CREATE TABLE IF NOT EXISTS skills(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	point_cost INTEGER NOT NULL,
	name TEXT NOT NULL,
	description TEXT NOT NULL,
	type INTEGER NOT NULL
)

CREATE TABLE IF NOT EXISTS steps(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	description TEXT NOT NULL,
	type INTEGER NOT NULL
)

CREATE TABLE IF NOT EXISTS unit_skills(
	unit_id INTEGER NOT NULL,
	skill_id INTEGER NOT NULL,
	[order] INTEGER NOT NULL
)

CREATE TABLE IF NOT EXISTS skill_steps(
	skill_id INTEGER NOT NULL,
	step_id INTEGER NOT NULL,
	[order] INTEGER NOT NULL,
	before_step_result INTEGER
)

CREATE TABLE IF NOT EXISTS action_step_data(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	step_id INTEGER NOT NULL,
	[value] TEXT NOT NULL,
	type INTEGER NOT NULL
)